CLOUDP-260778: Add config package
mongodb/atlas-cli-core pull request #1
Opened 2024-08-13 16:43 UTC by stefan4h

2024-08-13 17:04 UTC, jeroenvervaeke requested changes

2024-08-13 17:04 UTC, jeroenvervaeke commented on Makefile
> +	$(TEST_CMD) --tags="$(UNIT_TAGS)" -race -cover -count=1 -coverprofile $(COVERAGE) ./...
Can you also add a help command like in our other make files?

https://github.com/mongodb/mongodb-atlas-local/blob/4e26114ff4e7ac80d2edb00c5b8572b9f73c1d1b/Makefile#L112

2024-08-14 06:47 UTC, stefan4h commented on Makefile
> +	$(TEST_CMD) --tags="$(UNIT_TAGS)" -race -cover -count=1 -coverprofile $(COVERAGE) ./...
I don't have access to this repo but I've added a help command similar to the one in the Atlas CLI

2024-08-14 11:10 UTC, jeroenvervaeke commented on Makefile
> +	$(TEST_CMD) --tags="$(UNIT_TAGS)" -race -cover -count=1 -coverprofile $(COVERAGE) ./...
My bad, it's the same one

2024-08-14 11:10 UTC, jeroenvervaeke approved these changes

2024-08-14 11:11 UTC, merged